
# Drupal database
# - Database type: PostgreSQL
# - Database name: postgres
# - Database username: postgres
# - Database password: example

version: "2"
services:
  drupal:
    image: drupal:8.4-apache
    ports:
      - "8080:80"
    volumes:
      # Let the engine create volumes
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres:9.6
    environment:
      POSTGRE_PASSWORD: example

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: